# Generated by Django 3.2.16 on 2023-03-17 19:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('sample_id', models.AutoField(primary_key=True, serialize=False)),
                ('sampleName', models.CharField(max_length=250)),
                ('gender', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('age', models.IntegerField()),
                ('regimen', models.CharField(max_length=250)),
                ('viralLoad', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('samplingDate', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
