# Generated by Django 3.2.16 on 2023-03-17 19:41

from django.db import migrations, models
import django.utils.timezone
import uploads.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('projectID', models.AutoField(primary_key=True, serialize=False)),
                ('project_Name', models.CharField(max_length=50)),
                ('Region_Sequenced', models.CharField(max_length=50)),
                ('Sequencing_Technology', models.CharField(max_length=50)),
                ('Sequencing_Platform', models.CharField(max_length=50)),
                ('Sequencing_Date', models.DateField(default=django.utils.timezone.now)),
                ('fastq_Files', models.FileField(upload_to=uploads.models.project_upload_path)),
                ('sample_File', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('sample', models.AutoField(primary_key=True, serialize=False)),
                ('sampleName', models.CharField(max_length=250, unique=True)),
                ('samplingDate', models.DateField()),
                ('viralLoad', models.DecimalField(decimal_places=1, max_digits=10)),
                ('cd4', models.DecimalField(decimal_places=1, max_digits=10)),
                ('gender', models.CharField(max_length=250)),
                ('age', models.IntegerField()),
                ('literacy', models.CharField(max_length=250)),
                ('employment', models.CharField(max_length=250)),
                ('riskFactors', models.CharField(max_length=250)),
                ('maritalStatus', models.CharField(max_length=250)),
                ('regimen', models.CharField(max_length=250)),
                ('regimenStart', models.DateField()),
                ('project', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=50)),
                ('job_name', models.CharField(max_length=50)),
            ],
        ),
    ]
