# Generated by Django 3.2.16 on 2023-06-06 08:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_auto_20230606_0817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='sample_File',
            new_name='sample_CSV_File',
        ),
        migrations.RemoveField(
            model_name='project',
            name='Sequencing_Date',
        ),
        migrations.AddField(
            model_name='sample',
            name='Sequencing_Date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
