# Generated by Django 3.2.16 on 2023-03-17 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResults',
            fields=[
                ('analysis_results_id', models.AutoField(primary_key=True, serialize=False)),
                ('sample_ID', models.CharField(max_length=250)),
                ('drugClass', models.CharField(blank=True, max_length=250, null=True)),
                ('drugName', models.CharField(blank=True, max_length=250, null=True)),
                ('drugScore', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('susceptibility', models.CharField(blank=True, max_length=250, null=True)),
                ('project_ID', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MinorityVariantsResult',
            fields=[
                ('result', models.AutoField(primary_key=True, serialize=False)),
                ('chromosome', models.CharField(max_length=250)),
                ('gene', models.CharField(blank=True, max_length=250, null=True)),
                ('category', models.CharField(blank=True, max_length=250, null=True)),
                ('surveillance', models.CharField(blank=True, max_length=250, null=True)),
                ('wildtype', models.CharField(blank=True, max_length=250, null=True)),
                ('position', models.IntegerField()),
                ('mutation', models.CharField(blank=True, max_length=250, null=True)),
                ('mutation_frequency', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('coverage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sample', models.CharField(blank=True, max_length=250, null=True)),
                ('project', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewAnalysis',
            fields=[
                ('analysis_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_ID', models.CharField(max_length=250, unique=True)),
                ('description', models.CharField(default='DTG virological failure adults in Uganda', max_length=250)),
                ('email', models.EmailField(max_length=250)),
                ('mutation_Database', models.CharField(max_length=250)),
                ('consensus_Percentage', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ('target_Coverage', models.DecimalField(decimal_places=2, default=10000, max_digits=5)),
                ('length_Cutoff', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('score_Cutoff', models.DecimalField(decimal_places=2, default=30, max_digits=5)),
                ('error_Rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('minimum_Variant_Quality', models.DecimalField(decimal_places=2, default=0.01, max_digits=5)),
                ('minimum_Read_Depth', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('minimum_Allele_Count', models.DecimalField(decimal_places=2, default=0.01, max_digits=5)),
                ('minimum_Mutation_Frequency', models.DecimalField(decimal_places=2, default=0.01, max_digits=5)),
            ],
        ),
    ]
